# Generated by Django 3.0.7 on 2020-12-20 04:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('cedula', models.PositiveIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('nombre', models.CharField(max_length=150)),
                ('segundo_nombre', models.CharField(blank=True, max_length=150)),
                ('apellido', models.CharField(max_length=150)),
                ('segundo_apellido', models.CharField(blank=True, max_length=150)),
                ('sexo', models.CharField(choices=[('M', 'masculino'), ('F', 'femenino')], max_length=20)),
                ('num_contacto', models.IntegerField(blank=True, null=True)),
                ('representante', models.CharField(blank=True, max_length=150)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], max_length=150)),
                ('nota_memo', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('apellido', 'nombre'),
            },
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('descripcion', models.CharField(blank=True, max_length=1000, null=True)),
                ('status', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], max_length=150)),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'niveles',
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_lectivo', models.CharField(blank=True, max_length=150)),
                ('quimestre', models.IntegerField()),
                ('parcial', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Perfil_Profesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=250)),
                ('num_contacto', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], max_length=150)),
                ('nota_memo', models.TextField(blank=True)),
                ('nivel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academica.Nivel')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'perfil de profesor',
                'verbose_name_plural': 'perfiles de profesores',
                'ordering': ('-usuario',),
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('tipo', models.CharField(max_length=150)),
                ('publicada', models.BooleanField(default=False)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academica.Alumno')),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academica.Clase')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academica.Periodo')),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_lectivo', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999)])),
                ('status', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], max_length=150)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academica.Alumno')),
                ('nivel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='academica.Nivel')),
            ],
            options={
                'verbose_name': 'matrícula',
                'verbose_name_plural': 'matrículas',
                'ordering': ('alumno',),
            },
        ),
        migrations.CreateModel(
            name='Clase_Profesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academica.Clase')),
                ('profesor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academica.Perfil_Profesor')),
            ],
            options={
                'verbose_name': 'Profesor de Clase',
                'verbose_name_plural': 'Profesores de cada clase',
                'ordering': ('profesor',),
            },
        ),
        migrations.AddField(
            model_name='clase',
            name='nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academica.Nivel'),
        ),
    ]
