# Generated by Django 3.0.7 on 2020-12-20 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_auto_20201219_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicinfo',
            name='registration_no',
            field=models.IntegerField(default=148434, unique=True),
        ),
    ]
